name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *" # Run every 12 hours at 0 minutes
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Updated to v4 (Node.js 20)
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?palette=github-dark
            dist/snake-light.svg?palette=github-light
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4 # Updated to v4 (Node.js 20)
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
